### PR TITLE
feat: add /deactivate alias to /activate

### PR DESCRIPTION
**Pull request by rsdmike**

### CODE REVIEW

**Comment by rsdmike** [comment]
addresses open-amt-cloud-toolkit/rps#1017

**Comment by bwendlandt-intel** [comment]
I think we should aim for some more generic terminology. Because both /activate and /deactivate are misleading for maintenance commands so we'll probably still get the same ask again unless we want duplicate paths for each main RPC command.

I don't know exactly what it'd be, `/client`, `/amt`, `/rpc`, who knows, I haven't given that any thought if people have stronger opinions and ideas.

**Comment by madhavilosetty-intel** [comment]
May be we could use "/rps" instead of activate and deactivate. It will be generic for all the actions as @bwendlandt-intel suggested.

**Comment by tim-shockley** [comment]
What about changes to rpc-go ... usage for deactivate has the path in there too.
`	usage = usage + "              Example: " + executable + " deactivate -u wss://server/activate\n"`

**Comment by rsdmike** [comment]
> I think we should aim for some more generic terminology. Because both /activate and /deactivate are misleading for maintenance commands so we'll probably still get the same ask again unless we want duplicate paths for each main RPC command.
> 
> I don't know exactly what it'd be, `/client`, `/amt`, `/rpc`, who knows, I haven't given that any thought if people have stronger opinions and ideas.

/shrug It solves the issue filed by Corey, i'd say we just add a maintenance flag (along with a filed issue) if and when that need arises in a separate PR.

**Review by matt-primrose — APPROVED** [review]

**Comment by rsdmike** [comment]
> What about changes to rpc-go ... usage for deactivate has the path in there too. ` usage = usage + " Example: " + executable + " deactivate -u wss://server/activate\n"`

Yup, that would happen in the rpc-go repo.

**Pull request merged**
